### ISSUE TITLE
npm package issue

### ISSUE THREAD

**Issue by ryankall** [nishantmc/angular-material-fileupload#2]
This looks cool and great job so far. I tried running `npm i angular-material-fileupload` 
It installed fine but when i tried to compile it showed:

![image](https://user-images.githubusercontent.com/14932780/34847897-7b85a582-f6e2-11e7-9d2b-6af96ee53481.png)

![image](https://user-images.githubusercontent.com/14932780/34847927-9508810a-f6e2-11e7-97ad-1bb9cd87975e.png)

**Comment by nishantmc** [comment]
Hi Ryan, Thanks for taking a look at the package. Fixed the package and pushed to npm. Can you try the latest version (0.0.6)? Please let me know. once it compiles fine, be sure to link the google material icons in the index.html (check src/index.html) and import the material theme (check src/vendor.ts)

**Comment by ryankall** [comment]
The package now includes the the two component, however, I am getting different error which are puzzling.

When I run `ng sever`, the webpack complies. Then I tried using the component by uploading a file -> select a .png file  -> then error appears in web console:
![image](https://user-images.githubusercontent.com/14932780/34887623-ba1c7a1e-f78c-11e7-800c-f5351996ef1b.png)

The second thing is that my app is using angular cli. When I try to do a prod build which the command is: `ng build --prod && ng build --prod --app 1 --output-hashing=false`. I get this error during build.

```
ERROR in Error: Unexpected value 'MatFileUploadModule in C:/Users/RyanKall/WebstormProjects/project/node_modules/angular-material-fileupload/index.d.ts' imported by the module 'AppModule in
 C:/Users/RyanKall/WebstormProjects/project/src/app/app.module.ts'. Please add a @NgModule annotation.
```
Here is my ngModule:
![image](https://user-images.githubusercontent.com/14932780/34888009-22306ca4-f78e-11e7-8f33-4f2294857d06.png)


Note** Without MatFileUploadModule in my project all my commands work for all builds.

**Comment by nishantmc** [comment]
Ryan, on first issue, after publishing in npm i tested this package with the https://github.com/nishantmc/angular-webpack-starter (a basic starter app), couldn't see any issues. The FileUploadInputFor directive depends on dom native element https://nishantmc.github.io/angular-material-fileupload.github.io/directives/FileUploadInputFor.html#source. Can you check the dependencies in your package.json?

**Comment by ryankall** [comment]
I updated all the package in my package.json, resulting a different error.

![image](https://user-images.githubusercontent.com/14932780/35118576-c9365194-fc57-11e7-954e-b45d79705c40.png)

I create an example for you to see the error. I not sure what I am doing wrong at this point.
https://github.com/ryankall/example

For the Full build the error remain the same:
```
ERROR in Error: Unexpected value 'MatFileUploadModule in C:/Users/RyanKall/WebstormProjects/project/node_modules/angular-material-fileupload/index.d.ts' imported by the module 'AppModule in
 C:/Users/RyanKall/WebstormProjects/project/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by jmsunseri** [comment]
I am getting this exact same error:  

Unexpected value 'MatFileUploadModule' imported by the module 'AppModule'. Please add a @NgModule annotation

**Comment by nishantmc** [comment]
[patch.txt](https://github.com/nishantmc/angular-material-fileupload/files/1662826/patch.txt)
Ryan, i pushed version 0.0.8 (fix for dependency issue). I Was trying the example repo that you gave. I was able to make it work by changing the packages a bit. Please try to apply the patch.txt. Please let me know.

Justin, Can you try the latest version 0.0.8? also please check the package.json for the dependencies.

**Comment by jmsunseri** [comment]
still same error.  does it matter that I'm using Angular 4.4.6?

"dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/cdk": "^5.0.2",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/compiler-cli": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",
    "@angular/router": "^4.4.6",
    "@ngtools/webpack": "^1.8.0",
    "@types/webpack-env": "1.13.0",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "hammerjs": "^2.0.8",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "web-animations-js": "^2.3.1",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12",
    "moment": "^2.20.1",
    "angular-material-fileupload": "0.0.8"
  },




Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.

**Comment by nishantmc** [comment]
Can you try angular 5.1.2?

**Comment by jmsunseri** [comment]
Sorry it took me so long to get back to this but I have updated to 5.2.2 and now I'm getting the same error as @ryankall 

`ERROR Error: StaticInjectorError(AppModule)[FileUploadInputFor -> ElementRef]: 
  StaticInjectorError(Platform: core)[FileUploadInputFor -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!`

**Comment by ryankall** [comment]
Try it with 5.1.2 as he recommended and add apply the patch.txt . I will do it later today.

**Comment by ryankall** [comment]
@nishantmc 
I tried the patch but the problem still exist for me.
For the Full build the error remain the same ( npm run build:client-and-server-bundles):
```
ERROR in Error: Unexpected value 'MatFileUploadModule in C:/Users/RyanKall/WebstormProjects/project/node_modules/angular-material-fileupload/index.d.ts' imported by the module 'AppModule in
 C:/Users/RyanKall/WebstormProjects/project/src/app/app.module.ts'. Please add a @NgModule annotation.
```

I added you to my project so if you like to send me any updated I can just pull and run it.

**Comment by nishantmc** [comment]
Hi Ryan,
The steps i followed to test the app are
1) Clone example project
2) git apply patch.txt
3) npm install
4) npm start

I had a backend app running to which is the upload api. I tried just now and it works fine.
I tried the cmd npm run build:client-and-server-bundles, but yes it fails with the same error. I haven't used angular cli so not very sure abt the issue. I always use webpack to build the projects.

**Comment by nishantmc** [comment]
Also i pushed the patch to example repo so you can just pull the latest and try it.

**Comment by ryankall** [comment]
@nishantmc This seems to be an angular universal error. we can close this issue. Thank you.

**Comment by jmsunseri** [comment]
Have either of you identified a work around?

**Comment by nishantmc** [comment]
Justin, i think this issue is due to version conflicts between angular packages. https://github.com/ryankall/example is a working version. can you compare the packages in that repo with yours? I will be revisiting the dependent packages for angular-material-fileupload in some time. Will update on this.
