### ISSUE TITLE
Can't bind FileUploadFor & mat-file-upload-queue

### ISSUE THREAD

**Issue by jorgeherrera9103** [nishantmc/angular-material-fileupload#20]
Hi, I have two isssues when I used it in html component:

![fileuploadinput](https://user-images.githubusercontent.com/19397980/44113573-28dda3a8-9fce-11e8-8c98-f8b9a06c7060.png)

 and

![2018-08-14_14h24_46](https://user-images.githubusercontent.com/19397980/44113585-30126ffa-9fce-11e8-8eb8-5b3cb0ce28ee.png)

Thanks a lot.

**Comment by nishantmc** [comment]
Hi Jorge, Did you confirm that you imported the module?

**Comment by jorgeherrera9103** [comment]
Hi nishantmc, yes, of course

![image](https://user-images.githubusercontent.com/19397980/44148235-1420f5ac-a05d-11e8-8e5d-14cfc100306d.png)

**Comment by karkeedaniel** [comment]
+1

**Comment by jorgeherrera9103** [comment]
Never could fix it, so I changed,  thanks a lot.

**Comment by yikexiya** [comment]
I had the same problem. How did you solve it?

**Comment by yikexiya** [comment]
@jorgeherrera9103

**Comment by jorgeherrera9103** [comment]
hi @yikexiya no, I dedided to use other option.

**Comment by Gazoon007** [comment]
Any solution to fix this?

**Comment by jorgeherrera9103** [comment]
@Gazoon007  no, I decided to use other library for that.

**Comment by DanielFrugoni** [comment]
jorgeherrera9103 what are you sing ?

**Comment by jorgeherrera9103** [comment]
@DanielFrugoni I give up this way to do it. thanks a lot.
