### ISSUE TITLE
Tried to use the angular-material-fileupload component in my project, getting following error message

### ISSUE THREAD

**Issue by sudevanoa** [nishantmc/angular-material-fileupload#28]
index.html:37 Error: Unexpected token <
  Evaluating http://localhost:56526/angular-material-fileupload
  Evaluating http://localhost:56526/app/app.module.js
  Evaluating http://localhost:56526/app/main.js
  Loading app
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)
    at instantiate.js:394
    at dynamicExecute (register-loader.js:665)
    at doEvaluate (register-loader.js:612)
    at ensureEvaluate (register-loader.js:520)
    at register-loader.js:538
    at Object.eval (app.module.ts:18)
    at eval (app.module.ts:374)
    at eval (app.module.ts:374)

below is my package.json

{
  "name": "angular2-registration-login-example",
  "version": "1.0.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/cornflourblue/angular2-registration-login-example.git"
  },
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "module": "./esm5/service-worker.js",
  "es2015": "./esm2015/service-worker.js",
  "typings": "./service-worker.d.ts",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "6.1.7",
    "@angular/cdk": "^6.4.7",
    "@angular/cli": "^6.2.1",
    "@angular/common": "6.1.7",
    "@angular/compiler": "6.1.7",
    "@angular/core": "6.1.7",
    "@angular/forms": "6.1.7",
    "@angular/material": "6.4.7",
    "@angular/platform-browser": "6.1.7",
    "@angular/platform-browser-dynamic": "6.1.7",
    "@angular/router": "6.1.7",
    "angular-material-fileupload": "^1.0.1",
    "babel-core": "^6.26.3",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "jquery": "^3.0.1",
    "moment": "^2.22.2",
    "ng2-bs3-modal": "^0.13.0",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "^6.3.2",
    "rxjs-compat": "^6.3.2",
    "systemjs": "^0.20.19",
    "systemjs-plugin-babel": "0.0.25",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@types/node": "^8.0.53",
    "concurrently": "^3.1.0",
    "lite-server": "^2.4.0",
    "node-sass": "^4.9.3",
    "raw-loader": "^0.5.1",
    "sass-loader": "^7.0.3",
    "typescript": "^2.6.1",
    "babel-loader": "^7.1.5",
    "babel-preset-es2015": "^6.24.1"
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "skipMetadataEmit": false,
    "strictMetadataEmit": true,
    "annotationsAs": "decorators",
    "noImplicitAny": false
  }
}

**Comment by nishantmc** [comment]
Can you please provide the template html?

**Comment by andrefortin** [comment]
It seems to be an issue in your index.html file.

The message indicates you have an extra opening angle bracket '<'

**Comment by nishantmc** [comment]
@sudevanoa did you tried what @andrefortin said? Are you still seeing the issue?

**Comment by nishantmc** [comment]
closing the issue, Please feel free to reach out if you still have issues.
