### ISSUE TITLE
Not able to see the file upload and remove icons for individual files on the uploaded file list

### ISSUE THREAD

**Issue by chandrangreat** [nishantmc/angular-material-fileupload#29]
![icon-error](https://user-images.githubusercontent.com/15161522/47419600-2a55c680-d79a-11e8-942b-b08799e727fa.png)

**Comment by nishantmc** [comment]
Hi,
Please make sure you have material icons pulled in the app. To link google icons add
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> to the page.

**Comment by nishantmc** [comment]
@chandrangreat Are you still facing this issue?

**Comment by chandrangreat** [comment]
@nishantmc I am sorry, but I have moved on from that project and I did not do the above fixes at all. So I am not sure if the issue was resolved or not.

**Comment by nishantmc** [comment]
@chandrangreat oh ok, np, Will close this issue, feel free to open if you face again.

**Comment by hristovskivladimir** [comment]
still not working even with the stylesheet imported in my project also i have imported all required modules
