### ISSUE TITLE
No provider for ElementRef!

### ISSUE THREAD

**Issue by StefanRiedmann** [nishantmc/angular-material-fileupload#3]
Hi! 
Great package, but I've got this issue running your example code. The 'fileUploadInputFor' on the <input> element gives me that error. I'm running on
`    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-material-fileupload": "0.0.8",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"`

...and I imported the Modules
`  imports: [
    BrowserModule,
    HttpClientModule,
    FormsModule,
    BrowserAnimationsModule,
    MaterialModule,
    MatFileUploadModule
  ],`

(MaterialModule) is another export of all MaterialDesign modules. 

Detailed error:
OrdersComponent.html:22 ERROR Error: StaticInjectorError(AppModule)[FileUploadInputFor -> ElementRef]: 
  StaticInjectorError(Platform: core)[FileUploadInputFor -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at NgModuleRef_.get (core.js:12087)
    at resolveDep (core.js:12577)

**Comment by nishantmc** [comment]
Hi Stefan, Thanks for trying the package. Pushed an update. Can you try 0.0.9?

Just tried on a angular starter app with deps you gave me, looks fine. Please let me know.

     "@angular/animations": "^5.2.0",
      "@angular/cdk": "^5.2.4",
       "@angular/common": "^5.2.0", 
       "@angular/compiler": "^5.2.0",
        "@angular/core": "^5.2.0", 
        "@angular/forms": "^5.2.0", 
        "@angular/http": "^5.2.0", 
        "@angular/material": "^5.2.4", 
        "@angular/platform-browser": "^5.2.0", 
        "@angular/platform-browser-dynamic": "^5.2.0", 
        "@angular/router": "^5.2.0", 
        "angular-material-fileupload": "0.0.9", 
        "core-js": "^2.4.1", 
        "rxjs": "^5.5.6", 
        "zone.js": "^0.8.19"

**Comment by cedricschweizer** [comment]
Same problem... I'm currently running angular 8.1.1 could this be the reason why it's not working?

**Comment by david-roa** [comment]
Hi have problem, running angular 8.1.1 and angular-material-fileupload 2.0.0.. help please!

**Comment by cedricschweizer** [comment]
I don't think it's compatible with angular 8.1.1 tho...

**Comment by rajupenumatsa** [comment]
Same issue here. I tried with angular 8.1.1 with the latest angular-material-fileupload. Any help on this please.

**Comment by Jassem** [comment]
I tried with angular 8.3.14, and i have the same problem, I think it's not compatible with angular 8.x.
