### ISSUE TITLE
Upload not working in IE 11 error: Object doesn't support property or method 'set'

### ISSUE THREAD

**Issue by Ruchi-Sinha** [nishantmc/angular-material-fileupload#32]
HTML:
<input id="singleFile" type="file" [fileUploadInputFor]= "fileUploadQueue"/>
<mat-file-upload-queue #fileUploadQueue
      [fileAlias]="'file'"
      [httpUrl]="'http://localhost:8080/api'">-->
<mat-file-upload [file]="file" [id]="i" *ngFor="let file of fileUploadQueue.files; let i = index"></mat-file-upload>
</mat-file-upload-queue>

This is working fine in Chrome but when I try this in IE 11 the upload icon and Upload All button both throw error:

ERROR TypeError: Object doesn't support property or method 'set'
ERROR CONTEXT [object Object]

**Comment by Ruchi-Sinha** [comment]
Figured this one out. Error: Object doesn't support property or method 'set' is coming because IE 11 doesnot support formData.set() so changed it to formData.append() in all the files of angular-material-fileupload and it satrted working.

**Comment by script-newbie** [comment]
bro @Ruchi-Sinha  thanks for this you saved me a lot of time with this one.

**Comment by co0kie** [comment]
> bro @Ruchi-Sinha thanks for this you saved me a lot of time with this one.

hoi
