### ISSUE TITLE
Look and feel are different in IE 11 and chrome for same angular-material-fileupload code.

### ISSUE THREAD

**Issue by Ruchi-Sinha** [nishantmc/angular-material-fileupload#33]
HTML code:
`<input id="singleFile" type="file" [fileUploadInputFor]= "fileUploadQueue"/>
<mat-file-upload-queue #fileUploadQueue
      [fileAlias]="'file'"
       [httpUrl]="'http://localhost:8180/jax-rs-jersey-application-sample'">
<mat-file-upload [file]="file" [id]="i" *ngFor="let file of fileUploadQueue.files; let i = index"></mat-file-upload>
</mat-file-upload-queue>`

IE 11 it looks like below:

![ie](https://user-images.githubusercontent.com/26211351/49624847-31bdf000-fa27-11e8-8595-df8ba0a9562e.PNG)

Chrome it looks like below:

![chrome](https://user-images.githubusercontent.com/26211351/49624869-56b26300-fa27-11e8-8167-74532e0b7f7d.PNG)

**Comment by nishantmc** [comment]
@Ruchi-Sinha Are you talking about the Browse/ choose file button?

**Comment by nishantmc** [comment]
Closing this issue for now, Please feel free to reach out if you have questions.
