### ISSUE TITLE
@Angular/cli 7.1.4 and 7.3.1, Module does not compile

### ISSUE THREAD

**Issue by dallinwright** [nishantmc/angular-material-fileupload#36]
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-material-fileupload/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

Using this module with angular  >= 7.1.4 breaks compilation and does not work.

All you have to do is insert this line in app.module.ts and it breaks.

```import { MatFileUploadModule } from 'angular-material-fileupload';```

**Comment by nishantmc** [comment]
@dallinwright, i was trying with "@angular/cli": "~7.2.3" and "@angular/core": "~7.2.0". It worked fine.
Can you please share your package.json and tsconfig.json?

**Comment by Adam-Michalski** [comment]
I have the same issue 

tsconfig.json
`
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "paths": {
      "@app/*": ["app/*"],
      "@env/*": [
        "environments/*"
      ],
      "@testing/*": [
        "testing/*"
      ]
    },
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
`
tsconfig.app.json
`
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "",
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": ["node"]
  },
  "exclude": ["test.ts", "**/*.spec.ts"]
}
`
package.json dependencies

`
"dependencies": {
    "@angular/animations": "^7.0.3",
    "@angular/cdk": "^7.0.2",
    "@angular/common": "^7.0.3",
    "@angular/compiler": "^7.0.3",
    "@angular/core": "^7.0.3",
    "@angular/forms": "^7.0.3",
    "@angular/http": "^7.0.3",
    "@angular/material": "^7.0.2",
    "@angular/platform-browser": "^7.0.3",
    "@angular/platform-browser-dynamic": "^7.0.3",
    "@angular/router": "^7.0.3",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-free": "^5.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/free-brands-svg-icons": "^5.5.0",
    "@fortawesome/free-solid-svg-icons": "^5.5.0",
    "@ngrx/effects": "^7.0.0-beta.0",
    "@ngrx/entity": "^7.0.0-beta.0",
    "@ngrx/router-store": "^7.0.0-beta.0",
    "@ngrx/store": "^7.0.0-beta.0",
    "@ngrx/store-devtools": "^7.0.0-beta.0",
    "@ngx-translate/core": "^11.0.0",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-material-fileupload": "^2.0.0",
    "bootstrap": "^4.1.3",
    "browser-detect": "^0.2.28",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "^6.3.3",
    "uuid": "^3.3.2",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.10.4",
    "@angular-extensions/testing-library": "^3.0.3",
    "@angular/cli": "^7.0.4",
    "@angular/compiler-cli": "^7.0.3",
    "@angular/language-service": "^7.0.3",
    "@bahmutov/add-typescript-to-cypress": "^2.0.0",
    "@commitlint/cli": "^7.2.1",
    "@commitlint/config-conventional": "^7.1.2",
    "@compodoc/compodoc": "^1.1.7",
    "@types/jasmine": "~2.8.9",
    "@types/jasminewd2": "^2.0.5",
    "@types/node": "^10.12.2",
    "all-contributors-cli": "^5.4.1",
    "codelyzer": "~4.5.0",
    "cypress": "^3.1.3",
    "express": "^4.16.4",
    "husky": "^1.1.3",
    "jasmine-core": "~3.2.1",
    "jasmine-marbles": "^0.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.4",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "~1.3.1",
    "karma-spec-reporter": "~0.0.32",
    "lint-staged": "^7.3.0",
    "ngrx-store-freeze": "^0.2.4",
    "npm-run-all": "^4.1.5",
    "pa11y-ci": "^2.1.1",
    "prettier": "^1.14.3",
    "protractor": "^5.4.1",
    "rimraf": "^2.6.2",
    "standard-version": "4.2.0",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "^3.1.6",
    "webpack-bundle-analyzer": "^3.0.3"
  }
`

**Comment by nishantmc** [comment]
@dallinwright These are the deps i have on my test app. 

"dependencies": {
"@angular/animations": "~7.2.0",
"@angular/common": "~7.2.0",
"@angular/compiler": "~7.2.0",
"@angular/core": "~7.2.0",
"@angular/forms": "~7.2.0",
"@angular/platform-browser": "~7.2.0",
"@angular/platform-browser-dynamic": "~7.2.0",
"@angular/router": "~7.2.0",
"@angular/cdk": "~7.2.0",
"@angular/material": "~7.2.0",
"angular-material-fileupload": "2.0.0",
"core-js": "^2.5.4",
"rxjs": "~6.3.3",
"tslib": "^1.9.0",
"zone.js": "~0.8.26"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.12.0",
"@angular/cli": "~7.2.3",
"@angular/compiler-cli": "~7.2.0",
"@angular/language-service": "~7.2.0",
"@types/node": "~8.9.4",
"@types/jasmine": "~2.8.8",
"@types/jasminewd2": "~2.0.3",
"codelyzer": "~4.5.0",
"jasmine-core": "~2.99.1",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~3.1.1",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "~2.0.1",
"karma-jasmine": "~1.1.2",
"karma-jasmine-html-reporter": "^0.2.2",
"protractor": "~5.4.0",
"ts-node": "~7.0.0",
"tslint": "~5.11.0",
"typescript": "~3.2.2"
}

Let me know if this helps.

**Comment by nishantmc** [comment]
Also posting the tsconfig

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

**Comment by nishantmc** [comment]
@dallinwright Were you able to fix this?

**Comment by nishantmc** [comment]
Closing this for now. Please feel to reach out if you still facing the issue.
