### ISSUE TITLE
RequestHeaders not sent

### ISSUE THREAD

**Issue by Jonesie** [nishantmc/angular-material-fileupload#4]
Hi
Your component works very well for unauthenticated back ends, but I need to send a token to my api.  I see in matFileUpload.component.ts that headers is commented out.  Is there a reason for this?  Maybe there's a work around?

I tried to fork and build but that's too hard for me - too many errors :/

Cheers

**Comment by Jonesie** [comment]
Oh, never mind:  Interceptors :)

**Comment by nishantmc** [comment]
Hi Peter, Thanks for pointing out this commented code. Will take a look at it.
