### ISSUE TITLE
Error: Cannot find location of uploaded file on localhost web server.

### ISSUE THREAD

**Issue by Miega** [nishantmc/angular-material-fileupload#8]
I've been trying to figure out how and where an uploaded file goes, but I can only manage to get a 404 for the path I create.

The HTML side of things is basically unchanged, save for changing the [httpURL] value.

	<label for="singleFile">Upload file:</label>
	    <input class='file-upload' id="singleFile" type="file" [fileUploadInputFor]="fileUploadQueue" />
	    <br>
	    <mat-file-upload-queue #fileUploadQueue [fileAlias]="'file'" [httpUrl]="'http://localhost:4200/sample'">
	      <mat-file-upload [file]="file" [id]="i" *ngFor="let file of fileUploadQueue.files; let i = index"></mat-file-upload>
	    </mat-file-upload-queue>

Here's what I get after I upload a file:

	  POST http://localhost:4200/sample 404 (Not Found)
	  | scheduleTask | @ | zone.js:2935
	-- | -- | -- | --
	  | ZoneDelegate.scheduleTask | @ | zone.js:407
	  | onScheduleTask | @ | zone.js:297
	  | ZoneDelegate.scheduleTask | @ | zone.js:401
	  | Zone.scheduleTask | @ | zone.js:232
	  | Zone.scheduleMacroTask | @ | zone.js:255
	  | scheduleMacroTaskWithCurrentZone | @ | zone.js:1092
	  | (anonymous) | @ | zone.js:2967
	  | proto.(anonymous function) | @ | zone.js:1372
	  | (anonymous) | @ | http.js:2366
	  | Observable._trySubscribe | @ | Observable.js:172
	  | Observable.subscribe | @ | Observable.js:160
	  | subscribeToResult | @ | subscribeToResult.js:23
	  | MergeMapSubscriber._innerSub | @ | mergeMap.js:138
	  | MergeMapSubscriber._tryNext | @ | mergeMap.js:135
	  | MergeMapSubscriber._next | @ | mergeMap.js:118
	  | Subscriber.next | @ | Subscriber.js:92
	  | ScalarObservable._subscribe | @ | ScalarObservable.js:51
	  | Observable._trySubscribe | @ | Observable.js:172
	  | Observable.subscribe | @ | Observable.js:160
	  | MergeMapOperator.call | @ | mergeMap.js:92
	  | Observable.subscribe | @ | Observable.js:157
	  | MatFileUpload.upload | @ | matFileUpload.esm.js:150
	  | (anonymous) | @ | matFileUpload.esm.js:57
	  | QueryList.forEach | @ | core.js:6394
	  | MatFileUploadQueue.uploadAll | @ | matFileUpload.esm.js:57
	  | (anonymous) | @ | MatFileUploadQueue.html:3
	  | handleEvent | @ | core.js:13547
	  | callWithDebugContext | @ | core.js:15056
	  | debugHandleEvent | @ | core.js:14643
	  | dispatchEvent | @ | core.js:9962
	  | (anonymous) | @ | core.js:10587
	  | (anonymous) | @ | platform-browser.js:2628
	  | ZoneDelegate.invokeTask | @ | zone.js:421
	  | onInvokeTask | @ | core.js:4740
	  | ZoneDelegate.invokeTask | @ | zone.js:420
	  | Zone.runTask | @ | zone.js:188
	  | ZoneTask.invokeTask | @ | zone.js:496
	  | invokeTask | @ | zone.js:1517
	  | globalZoneAwareCallback | @ | zone.js:1543
	
Any clarification on this would be greatly appreciated.

**Comment by nishantmc** [comment]
Hi Miega, 
I didn't properly understand the question. so you are getting 404 for the api http://localhost:4200/sample. Did you try testing this api using postman or using some api testing tools?

**Comment by Miega** [comment]
I have tested this API with Postman, same result. I've even tried using just `http://localhost:4200` as another test, but the result is identical. Performing a file upload produces the same 404 error message.

Do you have a working demo or code example that shows an uploaded file? I'd like to see it and compare it to my own.

**Comment by nishantmc** [comment]
Looks like there is a misunderstanding. Do you have a service running which provides multipart file upload? for example a REST api. You should have a service which is accessible from this page to push files.

**Comment by Miega** [comment]
I see. I'm a bit new to REST API, so I may have misunderstood. Thanks for clarifying!
